// <auto-generated />
using System;
using ExampleAGAPI.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExampleAGAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231025020523_AlimentarTablaProducto")]
    partial class AlimentarTablaProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExampleAGAPI.Models.AGranel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Metros")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Frasco de Mani",
                            FechaActualizacion = new DateTime(2023, 10, 24, 22, 5, 23, 155, DateTimeKind.Local).AddTicks(7524),
                            FechaCreacion = new DateTime(2023, 10, 24, 22, 5, 23, 155, DateTimeKind.Local).AddTicks(7512),
                            ImageUrl = "",
                            Metros = 50,
                            Nombre = "Mani",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Frasco de Almendra",
                            FechaActualizacion = new DateTime(2023, 10, 24, 22, 5, 23, 155, DateTimeKind.Local).AddTicks(7527),
                            FechaCreacion = new DateTime(2023, 10, 24, 22, 5, 23, 155, DateTimeKind.Local).AddTicks(7526),
                            ImageUrl = "",
                            Metros = 20,
                            Nombre = "Almendra",
                            Ocupantes = 15,
                            Tarifa = 300.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
